### ISSUE TITLE
how can I get correct cuhksysu dataset?

### ISSUE THREAD

**Issue by xklstudio** [feifeiobama/PatchKD#1]
Hello! I have tried downloading the cuhksysu dataset from the given links, but no correct data is collected. Would you kindly offer a new link to the cuhksysu dataset? Thanks.

**Comment by feifeiobama** [comment]
Here are two links to correct data:
- Google Drive: https://drive.google.com/file/d/1z3LsFrJTUeEX3-XjSEJMOBrslxD2T5af
- Baidu Netdisk: https://pan.baidu.com/s/1jHLfeZk

Hope they can be useful for you!

**Comment by xklstudio** [comment]
Thanks a lot. Now I find I can't download the sensereid dataset, and the link in scenereid.py is not reachable. Could you please give me another link to get the sensereid dataset. Thanks again!

**Comment by feifeiobama** [comment]
I'm not sure if I can share the link. Please contact the first author of "Spindle Net: Person Re-identification with Human Body Region Guided Feature Decomposition and Fusion" to request the dataset, as I did.

**Comment by feifeiobama** [comment]
> Thanks a lot. Now I find I can't download the sensereid dataset, and the link in scenereid.py is not reachable. Could you please give me another link to get the sensereid dataset. Thanks again!

I'm not sure if I can share the link. Please contact the first author of "Spindle Net: Person Re-identification with Human Body Region Guided Feature Decomposition and Fusion" to request the dataset, as I did.

**Comment by xklstudio** [comment]
> > Thanks a lot. Now I find I can't download the sensereid dataset, and the link in scenereid.py is not reachable. Could you please give me another link to get the sensereid dataset. Thanks again!
> 
> I'm not sure if I can share the link. Please contact the first author of "Spindle Net: Person Re-identification with Human Body Region Guided Feature Decomposition and Fusion" to request the dataset, as I did.

Thanks for your reply!!! I will do as you suggest!
